# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# sidebar
sidebar: false
## Friends Link
friends:
  Yzzting: http://www.yzz1995.cn
  XenK0u: http://henbukexue.science
  Leyar: https://www.ileyar.com

# Analytics
## Baidu Analytics
baidu_analytics: e18a6d2c23f28ba7fdbf5d19d5356acc
## Google Analytics
google_analytics: UA-70950925-1

# Comments
## Duoshuo
# duoshuo_shortname: ahonn
## Disqus
disqus_shortname: swiftyper

# Social links
social:
  email: mailto:wordbeyondyoung@gmail.com
  github: https://github.com/buginux
  weibo: http://weibo.com/swiftyper
  # douban: https://www.douban.com/people/142374636
  jianshu: http://www.jianshu.com/users/3b40e55ec6d5/latest_articles
  rss: /atom.xml
  # twitter:
  # facebook:
  # zhihu: https://www.zhihu.com/people/ahonn
